// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNWKxN1xaSxNogcyyFwwAnoR70cGSyTs',
    appId: '1:953911914146:web:3af56c40a3005650f571fb',
    messagingSenderId: '953911914146',
    projectId: 'letterbook-35273',
    authDomain: 'letterbook-35273.firebaseapp.com',
    storageBucket: 'letterbook-35273.appspot.com',
    measurementId: 'G-4N446HPJ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYlGac-rId0Eqdlr8dI_akAUJofC4258',
    appId: '1:953911914146:android:f0689fd96f6bb1acf571fb',
    messagingSenderId: '953911914146',
    projectId: 'letterbook-35273',
    storageBucket: 'letterbook-35273.appspot.com',
  );
}
